[package]
name = "safec"
description = "A small, hackable, safety-oriented C compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "safec"
path = "src/main.rs"

[dependencies]
clap.workspace = true

[lints]
workspace = true
